### ISSUE TITLE
There are issues at RT

### ISSUE THREAD

**Issue by eserte** [Code-Hex/List-Flatten-XS#2] opened 2018-01-20 16:17 UTC
See https://rt.cpan.org/Ticket/Display.html?id=120902

**Comment by Code-Hex** [comment] 2018-01-21 01:51
@eserte Nice. I'm going to fix it today.

**Comment by Code-Hex** [comment] 2018-01-21 06:47
@eserte The issue is solved.
So if you check that It is solved, please close this issue.
Thanks.

**Comment by Code-Hex** [comment] 2018-01-22 23:28
@eserte ping

**Closed** 2018-01-29 14:16 UTC
